#!/bin/bash

########
# FUNC #
########

_color_group() {
    curr=$1
    count=$2
    offset=$((color - 1))
    echo -e "\n\n$1 ($color - $((color + count - 1))):"
}

_col_grp_modulo() {
    local base=${1:-$count}
    echo $(((color - offset) % base))
}

_print_colors() {
    local color= offset=

    for color in {0..255}
    do
        case $color in
            0)
                _color_group "Standard"    8
                ;;

            8)
                _color_group "Brighter"    8
                ;;

            16)
                _color_group "Devil Cube"  6
                ;;

            232)
                _color_group "Gray Scale" 24
                ;;
        esac

        printf "\e[%s;5;%sm%6s\e[0m" $ground $color $color

        [[ $(_col_grp_modulo) -ne 0 ]] || {
            echo
            [[ $curr != "Devil Cube" ]] || [[ $(_col_grp_modulo 36) -ne 0 ]] || echo
        }
    done
}

# PROGRAMS #

bg() {
    ground=48
    _print_colors
}

fg() {
    ground=38
    _print_colors
}


########
# INIT #
########

. .blang

argc=$#
argv=("$@")


########
# MAIN #
########

_process
