#! /bin/bash -e

dir=$1
exc=$2
tab=$3

while true; do 
    inotifywait -r -e modify "$dir" --exclude "$exc" && {
        # Seems i need a tiny delay for lisp, as if still loads the old file.
        sleep .1

        # Refresh chrome.
        xdotool search --desktop 0 "Chromium" \
                windowactivate --sync \
                key ctrl+"$tab" ctrl+r
    }
done
