#!/bin/bash
#


########
# rdy? #
########

calc() {
    bc -l <<< "$(parse "$STRING")"
}

parse() {
    echo "$@" | sed -E "s/(PI)/$PI/gi"
}

start() {
    while true
    do
        echo
        read -ep "Calculator: " STRING
        history -s "$STRING"
        calc
    done
}


########
# set. #
########

HISTFILE=/tmp/.calc_history

if [[ -z "$PI" ]]; then
    PI=$(echo "4*a(1)" | bc -l)
fi

STRING=


########
# go!! #
########

# trying to break out of the infinite loop in `start' but having to manually
# hit enter after Ctrl-C, but at least it writes to the history file...
trap 'break' INT

history -r $HISTFILE
start
history -w $HISTFILE
