#!/bin/bash

########
# rdy? #
########
calc() {
    bc -l <<< "$@"
}

parse() {
    echo "$@" | sed -E "s/PI|pi/$PI/g" # replace `PI|pi' with its value
}

start() {
    while true
    do
        echo
        read -ep "Calculator: " STRING
        STRING=$(parse "$STRING")
        store "$STRING"
        calc "$STRING"
    done
}

store() {
    LAST_STRING="$@"
    HIST+=("$@")
    # printf -- "- %s\n" "${HIST[@]}"
}

########
# set. #
########
if [[ -z "$PI" ]]; then
    PI=$(echo "4*a(1)" | bc -l)
fi

HIST=()
LAST_STRING=
STRING=

########
# go!! #
########
start
