#! /bin/bash -ue

##########
# ready? #
##########

########
# set. #
########
INT=LVDS1
EXT=$1; shift

#######
# go! #
#######
if (xrandr | grep "$EXT disconnected"); then
    echo "bye"
    xrandr --output $INT --auto --output $EXT --off 
else
    xrandr --output $INT --auto --primary \
           --output $EXT --auto "$@"
fi
