#!/bin/bash

#  Quadratic Bezier:  Q  control_x,y  x,y
#  Smooth " :         T  x,y

convert -size 100x60 xc:skyblue -fill white -stroke black  \
        -draw "path 'M 0,30   Q 25,15 50,30   T 100,30' " \
        /tmp/quad-bezier.gif
